version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-debug}
    ports:
      - target: 4567
        published: 8000
    networks:
      - sample-network
    volumes:
      - /var/log/:/hostlog/

networks:
  sample-network:
    driver: bridge
